# Generated by Django 4.1.7 on 2023-04-07 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_alter_expense_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
